version: "3.6"

services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    env_file:
      - ./.mysql.env

  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    env_file:
      - ./.mysql.env
    depends_on:
      - mysql
    volumes:
      - semaphore-inventory:/inventory
      - semaphore-keys:/authorized-keys
      - semaphore-config:/etc/semaphore

volumes:
  semaphore-mysql:
  semaphore-inventory:
  semaphore-keys:
  semaphore-config: