---
- hosts: vulnbox
  gather_facts: no
  remote_user: root
  tasks:
    - name: ssh-port
      set_fact:
        ansible_port: "{{ sshport }}"
        ansible_password: "{{ sshpassword }}"
    - ansible.builtin.import_role:
        name: init-vulnbox-users