---
- hosts: vulnbox
  gather_facts: no
  remote_user: root
  tasks:
    - name: ssh-port
      set_fact:
        ansible_port: "{{ sshport }}"
    - name: init-users
      import_role:
        name: init-vulnbox-users
    - name: enumerate-vulnbox
      import_role:
        name: vulnbox-enumeration
    - name: configure-suricata
      import_role:
        name: configure-suricata
      when: "{{ suricata|default(false)|bool == true }}"