---
# tasks file for vulnbox-enumeration
- name: Gather facts on listening ports
  community.general.listen_ports_facts:

- name: List all ports
  ansible.builtin.debug:
    msg: "{{ ':'.join((item.port|string, item.name)) }}"
  vars:
    ports: "{{ (ansible_facts.tcp_listen + ansible_facts.udp_listen) | rejectattr('address', 'equalto', '::') | list}}"
  loop: "{{ ports }}"

- name: List all users
  getent:
    database: passwd
    split: ':'

- debug:
    msg: "{{ getent_passwd | dict2items | map(attribute='key') | list }}"
